Run in Collab

In [1]:
pip install tensorflow-text


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.3/615.3 MB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 40.9 MB/s eta 0:00:00
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.17.1
    Uninstalling tensorboard-2.17.1:
      Successfully uninstalled tensorboard-2.17.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.17.1
    Uninstalling tensorflow-2.17.1:
      Successfully uninstalled tensorflow-2.17.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.18.0 which is incompatible.


In [2]:
import tensorflow_hub as hub
import tensorflow_text as text

In [3]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4"

In [4]:
bert_preprocess_model=hub.KerasLayer(preprocess_url)

In [5]:
text_test=['nice movie indeed','I love python programming']
text_preprocessed=bert_preprocess_model(text_test)
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [6]:
bert_model=hub.KerasLayer(encoder_url)
bert_results=bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [7]:
bert_results['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.79177403, -0.21411912,  0.49769545, ...,  0.24465235,
        -0.47334474,  0.81758696],
       [-0.91712314, -0.47935176, -0.7865697 , ..., -0.6175175 ,
        -0.71026856,  0.921843  ]], dtype=float32)>

In [8]:
bert_results['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292047,  0.08567817,  0.14476831, ..., -0.09677088,
          0.08722127,  0.07711085],
        [ 0.1783942 , -0.19006078,  0.5034952 , ..., -0.05869824,
          0.32717073, -0.15578493],
        [ 0.18701449, -0.43388748, -0.4887515 , ..., -0.15502778,
          0.00145182, -0.24471016],
        ...,
        [ 0.12083091,  0.12884252,  0.46453542, ...,  0.0737552 ,
          0.17441946,  0.16522075],
        [ 0.07967882, -0.01190652,  0.502254  , ...,  0.13777725,
          0.21002197,  0.00624588],
        [-0.07212701, -0.28303462,  0.59033376, ...,  0.475519  ,
          0.16668482, -0.08920349]],

       [[-0.0790059 ,  0.36335096, -0.21101595, ..., -0.17183761,
          0.16299714,  0.6724268 ],
        [ 0.27883548,  0.43716297, -0.35764822, ..., -0.04463654,
          0.38315183,  0.5887981 ],
        [ 1.2037671 ,  1.0727016 ,  0.48408663, ...,  0.24921048,
          0.407309  ,  0.40481755],
        ...,